homeassistant:
  name: Spark Home
  latitude: 12.9833
  longitude: 77.5833
  elevation: 928
  unit_system: metric
  time_zone: Asia/Kolkata
  customize: !include_dir_merge_named customize
frontend:

config:

http:
  api_password: !secret http_password
  ssl_certificate: /etc/live/shijupk.com/shijupk_bundle.pem
  ssl_key: /etc/live/shijupk.com/shijupk.key.pem
  base_url: shijupk.com

updater:
discovery:
conversation:

media_player:
  - platform: cast
history:
logbook:
map:

sun:

sensor:
  - platform: yr

tts:
  - platform: google

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
light: !include_dir_merge_list light
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensor
automation: !include automations.yaml
script: !include scripts.yaml
