homeassistant:
  name: Spark Home
  # Location required to calculate the time the sun rises and sets
  latitude: 12.9833
  longitude: 77.5833
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 928
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kolkata
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # ssl_certificate: /etc/live/shijupk.com/shijupk.com.pem
  # ssl_key: /etc/live/shijupk.com/shijupk.key.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: shijupk.com:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

light:
  - platform: hue
    host: 192.168.1.105
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

media_player:
  - platform: cast

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensor
automation: !include automations.yaml
script: !include scripts.yaml
